### ISSUE TITLE
WS.post_new_version - wrong upload URL

### ISSUE THREAD

**Issue by aszmyd** [eneongroup/hockeyapp#5]
```
[lib/hockeyapp/ws/ws.rb]
```

On line 70 there is:

```
"/apps/#{app_id}/app_versions"
```

as the upload url, but should be:

```
"/apps/#{app_id}/app_versions/upload"
```

Docs: http://support.hockeyapp.net/kb/api/api-versions#upload-version

**Comment by aimak** [comment]
Hello aszmyd,

Thanks for noticing me about that issue. You seem to be right. Do you happen to know if that endpoint changed recently ?

**Comment by aszmyd** [comment]
Sorry, I dont. I've just find it out during development on some new feature in work. Thanks for so quick response.

On May 9, 2014 4:55:17 PM CEST, Paul Renson notifications@github.com wrote:

> Hello aszmyd,
> 
> Thanks for noticing me about that issue. You seem to be right. Do you
> happen to know if that endpoint changed recently ?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/tapptic/hockeyapp/issues/5#issuecomment-42675013

## 

Pozdrawiam
Adam Szmyd

**Comment by aimak** [comment]
I pushed the changes. Thank you !
Let me know if something is still wrong.
